package com.jyg.qqcommon;

public enum MessageType {
    MESSAGE_LOGIN_SUCCESS, MESSAGE_lOGIN_FAIL, MESSAGE_COMMON, MESSAGE_GET_ONLINE_LIST,
    MESSAGE_RETURN_LIST, MESSAGE_CLIENT_EXIT, MESSAGE_COMMON_GROUP, MESSAGE_FILE;

}
